### ISSUE TITLE
"Make" failed

### ISSUE THREAD

**Issue by wc1018** [nrpy/nrpy#24]
I use  "mingw32-make" to make file in the wavetoy but it fails.
Details are represented below:
系统找不到指定的路径。
cc -O2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512ifma -mavx512vbmi  -g -Wall -Wno-unused-variable -std=gnu99  -c MoL_free_memory_non_y_n_gfs.c -o MoL_free_memory_non_y_n_gfs.o
process_begin: CreateProcess(NULL, cc -O2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512ifma -mavx512vbmi -g -Wall -Wno-unused-variable -std=gnu99 -c MoL_free_memory_non_y_n_gfs.c -o MoL_free_memory_non_y_n_gfs.o, ...) failed.
make (e=2):
Makefile:23: recipe for target 'MoL_free_memory_non_y_n_gfs.o' failed
mingw32-make: *** [MoL_free_memory_non_y_n_gfs.o] Error 2

**Comment by zachetienne** [comment]
Interesting. Have you confirmed that your C compiler (cc here) is capable of compiling C codes? Referring to issue #23  you are more likely to achieve success if you use WSL, Linux, or MacOS as NRPy is untested in pure Windows environments.
